CreatorDev/Ci40-platform-feed

cgilua/Makefile

Update cgilua package feed to clone the repository instead of downloading tar

---

wpa_supplicant/Makefile

add wpa_supplicant package feed

---

wpa_supplicant/Makefile

correct wpa_supplicant package title

---

README.md
fping/Makefile

Add fping package

---

README.md
awalwm2m/Makefile
awalwm2m/files/etc/config/awalwm2m
awalwm2m/files/etc/init.d/awa_bootstrapd
awalwm2m/files/etc/init.d/awa_clientd
awalwm2m/files/etc/init.d/awa_serverd
awalwm2m/files/etc/rc.d/K10awa_bootstrapd
awalwm2m/files/etc/rc.d/K10awa_clientd
awalwm2m/files/etc/rc.d/K10awa_serverd
awalwm2m/files/etc/rc.d/S98awa_bootstrapd
awalwm2m/files/etc/rc.d/S98awa_clientd
awalwm2m/files/etc/rc.d/S98awa_serverd
awalwm2m/files/usr/bin/setup_demo
webscripts/Makefile
webscripts/files/provision.cfg

Signed-off-by: Abhijit Mahajani Abhijit.Mahajani@imgtec.com

Add awalwm2m and webscripts feed

---

README.md
click_apps/Makefile

Signed-off-by: Pratik Prajapati <Pratik.Prajapati@imgtec.com>

Add click apps package

---

awalwm2m/Makefile
awalwm2m/files/etc/init.d/awa_bootstrapd
awalwm2m/files/etc/init.d/awa_clientd
awalwm2m/files/etc/init.d/awa_serverd

Also update binary path in Init scripts.
Signed-off-by: Pratik Prajapati <Pratik.Prajapati@imgtec.com>

Update awalwm2m version to 0.1.10

---

click_apps/Makefile
u-boot/Makefile

Update u-boot and click_apps feeds to pull from CreatorDev

---

u-boot/Makefile

Add version number in uboot binary

---

README.md

Update Readme with CreatorDev

---

board-test/Makefile

Signed-off-by: Francois Berder <Francois.Berder@imgtec.com>

Add board-test package

---

board-test/Makefile

add alsa-utils-tests as board-test package dependency

---

ca8210/Makefile

Update ca8210 feed to pull from public repo

---

board-test/Makefile

board-test feed: increase version to 0.1.1

---

board-test/Makefile

Update board-test feeds to pull from CreatorDev

---

ca8210/Makefile

Signed-off-by: Shraddha Chaudhari <Shraddha.Chaudhari@imgtec.com>

ca8210: select package version 1.1 for kernel version 4.4

---

letmecreate/Config.in
letmecreate/Makefile

Signed-off-by: Pratik Prajapati <Pratik.Prajapati@imgtec.com>

letmecreate: add feed

---

totd/Makefile
totd/files/totd.conf
totd/files/totd.init
totd/files/totd_configure_dhcp

Signed-off-by: bartlomiej.zarnowski <bartlomiej.zarnowski@imgtec.com>

add totd deamon

---

README.md

Signed-off-by: Nikhil Zinjurde <nikhil.zinjurde@imgtec.com>

Update README.md and add Contributor's guide link

---

tpm-tools/Makefile
tpm-tools/patches/001-tpm_nvread-include-sys-stat-header.patch
tpm-tools/patches/002-remove-Werror.patch
trousers/Makefile
trousers/files/tcsd.conf
trousers/files/tcsd.init
trousers/patches/001-remove-inline-for-read_data-and-write_data.patch
trousers/patches/003-musl-limits-h.patch
trousers/patches/004-getpwent_r-only.patch

Also includes tpm tools to help managing/testing
Requires kernel tpm support https://github.com/CreatorDev/openwrt/pull/139

Add trousers tss stack to manage tpm

---

README.md

Signed-off-by: Nikhil Zinjurde <nikhil.zinjurde@imgtec.com>

Update README.md to change repo name title

---

uboot-pistachio/Makefile
uboot-pistachio/patches/001-MIPS_extern_to_static.patch

Fuzz patches to fit new code base.
Signed-off-by: Ian Pozella <Ian.Pozella@imgtec.com>

uboot-pistachio: bump to release 0.2.0

---

README.md

* Remove awalwm2m
* Add tpm-tools and trousers
Signed-off-by: Nikhil Zinjurde <nikhil.zinjurde@imgtec.com>

README.md: update readme with package information

---

README.md
uccp420wlan/Makefile
uccp420wlan/files/etc/init.d/uccp420wlan

Signed-off-by: Francois Berder <francois.berder@imgtec.com>
This connects CreatorDev/openwrt#60

Add uccp420wlan package

---

uccp420wlan/Makefile
uccp420wlan/files/etc/init.d/uccp420wlan

this connects CreatorDev/openwrt#106.

Update wifi driver according to changes in u-boot

---

Jenkinsfile

The job we trigger updated it so this brings us back in sync.
The connects CreatorDev/openwrt#176

Jenkinsfile: update triggered build param name

---

board-test/Makefile

This connects to CreatorDev/openwrt#185
Signed-off-by: Francois Berder <francois.berder@imgtec.com>

board-test: update to version 0.1.2
